# Generated by Django 3.2.5 on 2021-08-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATKQueue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datetimeslot',
            options={'ordering': ('-date_reserve', 'slot'), 'verbose_name_plural': 'ตารางวันเวลา [DateTimeSlot]'},
        ),
        migrations.AlterField(
            model_name='queue',
            name='created',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='queue',
            name='modified',
            field=models.DateTimeField(blank=True),
        ),
    ]
