# Generated by Django 3.2.5 on 2021-07-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corona3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corona3',
            name='BirthYear',
            field=models.IntegerField(verbose_name='พ.ศ.เกิด'),
        ),
        migrations.AlterField(
            model_name='corona3',
            name='BookReceivedVaccine',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='จองวัคซีน'),
        ),
        migrations.AlterField(
            model_name='corona3',
            name='FullName',
            field=models.CharField(max_length=255, verbose_name='ชื่อผู้ป่วย'),
        ),
        migrations.AlterField(
            model_name='corona3',
            name='HospitalProvince',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='สถานพยาบาลอยู่ในจังหวัด'),
        ),
        migrations.AlterField(
            model_name='corona3',
            name='LiveInCovid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ที่อาศัยมีการระบาด COVID'),
        ),
        migrations.AlterField(
            model_name='corona3',
            name='ReceivedVaccine',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='เคยรับวัคซีน'),
        ),
    ]
