# Generated by Django 3.2.5 on 2021-07-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0001_initial'),
        ('Corona3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corona3',
            name='Patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Patient_colona3', to='Patient.patient'),
        ),
    ]
