# Generated by Django 3.2.5 on 2021-07-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0001_initial'),
        ('Corona3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corona3',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Patient', to='Patient.patient', verbose_name='เลขประชาชน'),
        ),
    ]
