# Generated by Django 3.2.4 on 2021-08-01 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corona3', '0002_auto_20210731_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='corona3',
            name='ATK',
            field=models.FileField(blank=True, null=True, upload_to='Corona3/'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='AirforceType',
            field=models.IntegerField(choices=[(0, 'ไม่ระบุ'), (1, 'ทหารประจำการ'), (2, 'พลทหาร'), (3, 'พนง.ราชการ'), (4, 'ลูกจ้างประจำ'), (5, 'ลูกจ้างชั่วคราว'), (6, 'ครอบครัว ทอ.'), (7, 'บุคคลภายนอก')], default=0, null=True, verbose_name='ประเภทข้าราชการ'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='BloodType',
            field=models.CharField(blank=True, default='-', max_length=3, null=True, verbose_name='กรุปเลือด'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='CurrentStatus',
            field=models.IntegerField(choices=[(0, 'ไม่ระบุ'), (1, 'ผู้ป่วยสีเขียว - ไม่มีอาการ'), (2, 'ผู้ป่วยสีเหลืองอ่อน - ไข้ต่ำ'), (3, 'ผู้ป่วยสีเหลืองเข้ม - ไข้สูง'), (4, 'ผู้ป่วยสีแดง - ไข้สูงมาก')], default=0, null=True, verbose_name='สถานะผู้ป่วยปัจจุบัน'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='DrugAllergyHistory',
            field=models.CharField(blank=True, default='-', max_length=300, null=True, verbose_name='ประวัติการแพ้ยา'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='Email',
            field=models.CharField(blank=True, default='-', max_length=200, null=True, verbose_name='กรุปเลือด'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='GoogleMap',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Google Map Code'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='HomeIsolation',
            field=models.IntegerField(choices=[(0, 'ไม่ระบุ'), (1, 'ได้'), (2, 'ไม่ได้')], default=0, null=True, verbose_name='สามารถทำ Home Isolation'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='LiveWith',
            field=models.CharField(blank=True, default='-', max_length=5, null=True, verbose_name='จำนวนผู้พักอาศัยร่วม'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='MobileRelative',
            field=models.CharField(default='-', max_length=20, null=True, verbose_name='เบอร์โทรญาติ'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='Note',
            field=models.CharField(blank=True, default='-', max_length=300, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='PCR',
            field=models.FileField(blank=True, null=True, upload_to='Corona3/'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='Religion',
            field=models.CharField(blank=True, default='-', max_length=15, null=True, verbose_name='ศาสนา'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='RightMedicalTreatment',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'เบิกจ่ายตรง (กรมบัญชีกลาง)'), (2, 'ประกันสังคม'), (3, 'UC (สปสช.)'), (4, 'เงินสด')], default=0, null=True, verbose_name='สิทธิ์การรักษาพยาบาล'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='Symptom',
            field=models.CharField(blank=True, default='-', max_length=300, null=True, verbose_name='อาการ'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='TreatPlaceWork',
            field=models.CharField(blank=True, default='-', max_length=250, null=True, verbose_name='ต้นสังกัดที่เบิกค่ารักษาพยาบาล'),
        ),
        migrations.AddField(
            model_name='corona3',
            name='VaccineDetail',
            field=models.CharField(blank=True, default='-', max_length=200, null=True, verbose_name='ข้อมูลการรับวัคซีน'),
        ),
        migrations.AlterField(
            model_name='corona3',
            name='DateReport',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='วันที่'),
        ),
    ]
