# Generated by Django 3.2.5 on 2021-07-31 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Corona3', '0002_corona3_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corona3',
            old_name='InThaiProvice',
            new_name='InThaiProvince',
        ),
    ]
