# Generated by Django 3.2.5 on 2021-08-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corona3', '0003_auto_20210801_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corona3',
            name='BloodType',
            field=models.CharField(blank=True, default='-', max_length=3, null=True, verbose_name='หมู่เลือด'),
        ),
        migrations.AlterField(
            model_name='corona3',
            name='Email',
            field=models.CharField(blank=True, default='-', max_length=200, null=True, verbose_name='EMail'),
        ),
        migrations.AlterField(
            model_name='corona3',
            name='NameVaccine1',
            field=models.CharField(blank=True, choices=[('-', '-'), ('1', 'Sinovac'), ('2', 'Astra Zeneca'), ('3', 'Pfizer'), ('4', 'Moderna')], default='-', max_length=20, null=True, verbose_name='ชื่อวัคซีน'),
        ),
        migrations.AlterField(
            model_name='corona3',
            name='NameVaccine2',
            field=models.CharField(blank=True, choices=[('-', '-'), ('1', 'Sinovac'), ('2', 'Astra Zeneca'), ('3', 'Pfizer'), ('4', 'Moderna')], default='-', max_length=20, null=True, verbose_name='ชื่อวัคซีน'),
        ),
    ]
