# Generated by Django 3.2.5 on 2021-08-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corona3', '0004_auto_20210818_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corona3',
            name='CaseFemale',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'ไม่ตั้งครรภ์'), ('2', 'ตั้งครรภ์')], default='0', max_length=15, null=True, verbose_name='กรณีเพศหญิง'),
        ),
        migrations.AlterField(
            model_name='corona3',
            name='DiseasePatient',
            field=models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='โรคประจำตัว'),
        ),
        migrations.AlterField(
            model_name='corona3',
            name='ResultsCheckRTPCR',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'Detected'), ('2', 'Not Detected')], default='0', max_length=50, null=True, verbose_name='ผลการตรวจ RT PCR'),
        ),
        migrations.AlterField(
            model_name='corona3',
            name='ShowSymptom',
            field=models.CharField(blank=True, choices=[('1', 'ไม่มีอาการใด ๆ'), ('2', 'มีอาการ แต่ไม่มีอาการระบบทางเดินหายใจ'), ('3', 'มีอาการระบบทางเดินหายใจ และระบุ O2Sat %')], default='1', max_length=200, null=True, verbose_name='อาการและอาการแสดง(ณ วันที่รายงาน)'),
        ),
        migrations.AlterField(
            model_name='corona3',
            name='ShowSymptom_O2',
            field=models.CharField(blank=True, default='1', max_length=3, null=True, verbose_name='ค่า O2 Sat %'),
        ),
        migrations.AlterField(
            model_name='corona3',
            name='TypeViolence',
            field=models.CharField(blank=True, choices=[('0', 'ไม่ระบุ'), ('1', 'เป็นปอดอักเสบ'), ('2', 'ใส่เครื่องช่วยหายใจ'), ('3', 'เสียชีวิต')], default='0', max_length=20, null=True, verbose_name='ความรุนแรงของอาการ'),
        ),
    ]
