# Generated by Django 3.2.5 on 2021-08-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corona3', '0005_auto_20210818_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corona3',
            name='CareerPatient',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='อาชีพ(ระบุลักษณะงาน เช่น บุคลากรทางการแพทย์)'),
        ),
    ]
