# Generated by Django 3.2.5 on 2021-07-25 04:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMEDPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonID', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='เลขบัตรประชาชน')),
                ('HNNumber', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='เลขผู้ป่วยนอก')),
                ('ANNumber', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='เลขผู้ป่วยใน')),
                ('FullName', models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='ชื่อผู้ป่วย')),
                ('Mobile', models.CharField(blank=True, max_length=10, null=True, verbose_name='เบอร์มือถือ')),
                ('Symtom', models.IntegerField(choices=[(0, 'ไม่ระบุ'), (1, 'ผู้ป่วยสีเขียว'), (2, 'ผู้ป่วยสีเหลืองอ่อน'), (3, 'ผู้ป่วยสีเหลืองเข้ม'), (4, 'ผู้ป่วยสีแดง'), (5, 'หายป่วย'), (6, 'เสียชีวิต'), (7, 'ผู้ใกล้ชิดเสี่ยงสูง'), (8, 'ผู้ใกล้ชิดปลอดเชื้อ'), (9, 'ผู้ใกล้ชิดติดเชื้อ')], default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'ตารางผู้ป่วย AMED [AMED Patient]',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today, verbose_name='วันที่')),
                ('FullName', models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='ชื่อผู้ป่วย')),
                ('Gender', models.CharField(blank=True, choices=[('-', 'ไม่ระบุ'), ('ช', 'ชาย'), ('ญ', 'หญิง')], default='-', max_length=8, null=True)),
                ('BirthDay', models.DateField(blank=True, null=True, verbose_name='วันเกิด')),
                ('PersonID', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='เลขบัตรประชาชน')),
                ('Office', models.TextField(blank=True, default=None, null=True, verbose_name='ที่ทำงาน/สังกัด')),
                ('IsAirforce', models.BooleanField(blank=True, default=False, null=True, verbose_name='ขรก.ทอ.')),
                ('DatePositive', models.DateField(blank=True, null=True, verbose_name='วันที่ตรวจพบเชื้อ')),
                ('CurrentStatus', models.IntegerField(choices=[(0, 'ไม่ระบุ'), (1, 'ผู้ป่วยสีเขียว'), (2, 'ผู้ป่วยสีเหลืองอ่อน'), (3, 'ผู้ป่วยสีเหลืองเข้ม'), (4, 'ผู้ป่วยสีแดง'), (5, 'หายป่วย'), (6, 'เสียชีวิต'), (7, 'ผู้ใกล้ชิดเสี่ยงสูง'), (8, 'ผู้ใกล้ชิดปลอดเชื้อ'), (9, 'ผู้ใกล้ชิดติดเชื้อ')], default=0, null=True, verbose_name='สถานะผู้ป่วยปัจจุบัน')),
                ('CurrentTreatment', models.IntegerField(choices=[(0, 'ไม่ระบุ'), (1, 'รักษาระยะห่าง'), (2, 'กักตัวอยู่บ้าน'), (3, 'กักตัวรอเตียง'), (4, 'Home Isolation'), (5, 'รพ.สนาม'), (6, 'โรงพยาบาล'), (7, 'ICU')], default=0, null=True, verbose_name='การรักษาปัจจุบัน')),
                ('Mobile', models.CharField(blank=True, max_length=10, null=True, verbose_name='เบอร์มือถือ')),
                ('Address', models.TextField(blank=True, default=None, null=True, verbose_name='ที่อยู่ปัจจุบัน')),
                ('RightMedicalTreatment', models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'เบิกจ่ายตรง (กรมบัญชีกลาง)'), (2, 'ประกันสังคม'), (3, 'UC (สปสช.)'), (4, 'เงินสด')], default=0, null=True, verbose_name='สิทธิ์การรักษาพยาบาล')),
                ('Corona3', models.FileField(blank=True, null=True, upload_to='Corona3/')),
                ('DetectedResult', models.FileField(blank=True, null=True, upload_to='Corona3/')),
                ('EmergencyMobile', models.CharField(blank=True, max_length=10, null=True, verbose_name='เบอร์ฉุกเฉิน')),
                ('ConfirmedByCRC', models.BooleanField(blank=True, default=False, null=True, verbose_name='แพทย์ยืนยันข้อมูล')),
                ('IsAMED', models.BooleanField(blank=True, default=False, null=True, verbose_name='มีข้อมูลใน AMED')),
                ('Comment', models.TextField(blank=True, default=None, null=True, verbose_name='หมายเหตุ')),
                ('ConfirmUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ConfirmUser', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ยืนยันข้อมูล ')),
                ('DataUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DataUser', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('InfectiousName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Infectious_Name', to='Patient.patient', verbose_name='ชื่อคนแพร่เชื้อ')),
            ],
            options={
                'verbose_name_plural': 'ตารางผู้ป่วย [Patient]',
            },
        ),
        migrations.CreateModel(
            name='TreatmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True, verbose_name='วันที่บันทึก')),
                ('Treatment', models.IntegerField(choices=[(0, 'ไม่ระบุ'), (1, 'รักษาระยะห่าง'), (2, 'กักตัวอยู่บ้าน'), (3, 'กักตัวรอเตียง'), (4, 'Home Isolation'), (5, 'รพ.สนาม'), (6, 'โรงพยาบาล'), (7, 'ICU')], default=1, null=True)),
                ('Comment', models.TextField(blank=True, default=None, null=True, verbose_name='คำอธิบาย')),
                ('RecorderUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TreatmentLogUser', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึกข้อมูล')),
                ('ThePatient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PatientLogTreament', to='Patient.patient', verbose_name='ชื่อผู้ป่วย')),
            ],
            options={
                'verbose_name_plural': 'ตารางแสดงการรักษาผู้ป่วย [TreatmentLog]',
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True, verbose_name='วันที่บันทึก')),
                ('Status', models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'ผู้ป่วยสีเขียว'), (2, 'ผู้ป่วยสีเหลืองอ่อน'), (3, 'ผู้ป่วยสีเหลืองเข้ม'), (4, 'ผู้ป่วยสีแดง'), (5, 'หายป่วย'), (6, 'เสียชีวิต'), (7, 'ผู้ใกล้ชิดเสี่ยงสูง'), (8, 'ผู้ใกล้ชิดปลอดเชื้อ'), (9, 'ผู้ใกล้ชิดติดเชื้อ')], default=1, null=True)),
                ('Comment', models.TextField(blank=True, default=None, null=True, verbose_name='คำอธิบาย')),
                ('RecorderUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='StatusRecorderUser', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึกข้อมูล')),
                ('ThePatient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PatientName', to='Patient.patient', verbose_name='ชื่อผู้ป่วย')),
            ],
            options={
                'verbose_name_plural': 'ตารางสถานะผู้ป่วย [StatusLog]',
            },
        ),
    ]
