# Generated by Django 3.2.5 on 2021-07-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='EmergencyMobileMobile',
            new_name='EmergencyMobile',
        ),
        migrations.AddField(
            model_name='patient',
            name='IsAirforce',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ขรก.ทอ.'),
        ),
    ]
