# Generated by Django 3.2.5 on 2021-08-02 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amedpatient',
            name='Mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์มือถือ'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='AirforceType',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'ทหารประจำการ'), (2, 'พลทหาร'), (3, 'พนง.ราชการ'), (4, 'ลูกจ้างประจำ'), (5, 'ลูกจ้างชั่วคราว'), (6, 'ครอบครัว ทอ.'), (7, 'บุคคลภายนอก')], default=0, null=True, verbose_name='ประเภทข้าราชการ'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='CurrentStatus',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'ผู้ป่วยสีเขียว'), (2, 'ผู้ป่วยสีเหลืองอ่อน'), (3, 'ผู้ป่วยสีเหลืองเข้ม'), (4, 'ผู้ป่วยสีแดง'), (5, 'หายป่วย'), (6, 'เสียชีวิต'), (7, 'ผู้ใกล้ชิดเสี่ยงสูง'), (8, 'ผู้ใกล้ชิดปลอดเชื้อ'), (9, 'ผู้ใกล้ชิดติดเชื้อ')], default=0, null=True, verbose_name='สถานะผู้ป่วยปัจจุบัน'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='CurrentTreatment',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'รักษาระยะห่าง'), (2, 'กักตัวอยู่บ้าน'), (3, 'กักตัวรอเตียง'), (4, 'Home Isolation'), (5, 'รพ.สนาม'), (6, 'โรงพยาบาล'), (7, 'ICU')], default=0, null=True, verbose_name='การรักษาปัจจุบัน'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='DataUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DataUser', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='EmergencyMobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์ฉุกเฉิน'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์มือถือ'),
        ),
    ]
