# Generated by Django 3.2.5 on 2021-07-22 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentlog',
            name='RecorderUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TreatmentLogUser', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึกข้อมูล'),
        ),
        migrations.AddField(
            model_name='treatmentlog',
            name='ThePatient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PatientLogTreament', to='Patient.patient', verbose_name='ชื่อผู้ป่วย'),
        ),
        migrations.AddField(
            model_name='statuslog',
            name='RecorderUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='StatusRecorderUser', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึกข้อมูล'),
        ),
        migrations.AddField(
            model_name='statuslog',
            name='ThePatient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PatientName', to='Patient.patient', verbose_name='ชื่อผู้ป่วย'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ConfirmUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ConfirmUser', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ยืนยันข้อมูล '),
        ),
        migrations.AddField(
            model_name='patient',
            name='DataUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='DataUser', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='patient',
            name='InfectiousName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Infectious_Name', to='Patient.patient', verbose_name='ชื่อคนแพร่เชื้อ'),
        ),
    ]
