# Generated by Django 3.2.5 on 2021-07-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='ConfirmedPatient',
            new_name='ConfirmedByCRC',
        ),
    ]
