# Generated by Django 3.2.5 on 2021-07-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_rename_confirmedpatient_patient_confirmedbycrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='IsAMED',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='มีข้อมูลใน AMED'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='CurrentStatus',
            field=models.IntegerField(choices=[(0, 'ไม่ระบุ'), (1, 'ผู้ป่วยสีเขียว'), (2, 'ผู้ป่วยสีเหลืองอ่อน'), (3, 'ผู้ป่วยสีเหลืองเข้ม'), (4, 'ผู้ป่วยสีแดง'), (5, 'หายป่วย'), (6, 'เสียชีวิต'), (7, 'ผู้ใกล้ชิดเสี่ยงสูง'), (8, 'ผู้ใกล้ชิดปลอดเชื้อ'), (9, 'ผู้ใกล้ชิดติดเชื้อ')], default=0, null=True, verbose_name='สถานะผู้ป่วยปัจจุบัน'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='CurrentTreatment',
            field=models.IntegerField(choices=[(0, 'ไม่ระบุ'), (1, 'รักษาระยะห่าง'), (2, 'กักตัวอยู่บ้าน'), (3, 'กักตัวรอเตียง'), (4, 'Home Isolation'), (5, 'รพ.สนาม'), (6, 'โรงพยาบาล'), (7, 'ICU')], default=0, null=True, verbose_name='การรักษาปัจจุบัน'),
        ),
    ]
