# Generated by Django 3.2.5 on 2021-07-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_remove_patient_airforcetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='AirforceType',
            field=models.IntegerField(choices=[(0, 'ไม่ระบุ'), (1, 'ทหารประจำการ'), (2, 'พลทหาร'), (3, 'ครอบครัว'), (4, 'บุคคลภายนอก')], default=0, null=True, verbose_name='ประเภทข้าราชการ'),
        ),
    ]
