# Generated by Django 3.2.5 on 2021-07-21 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_auto_20210721_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='ThePatient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PatientName', to='Patient.patient', verbose_name='ชื่อผู้ป่วย'),
        ),
        migrations.AlterField(
            model_name='treatmentlog',
            name='ThePatient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PatientLogTreament', to='Patient.patient', verbose_name='ชื่อผู้ป่วย'),
        ),
    ]
