# Generated by Django 3.2.5 on 2021-07-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_patient_airforcetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Office',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='ที่ทำงาน/สังกัด'),
        ),
    ]
