# Generated by Django 3.2.5 on 2021-07-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_alter_patient_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='amedpatient',
            name='Comment',
            field=models.TextField(blank=True, null=True, verbose_name='คำอธิบาย'),
        ),
        migrations.AddField(
            model_name='amedpatient',
            name='Report',
            field=models.TextField(blank=True, null=True, verbose_name='รายงานใน AMED'),
        ),
        migrations.AddField(
            model_name='amedpatient',
            name='RightMedicalTreatment',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'เบิกจ่ายตรง (กรมบัญชีกลาง)'), (2, 'ประกันสังคม'), (3, 'UC (สปสช.)'), (4, 'เงินสด')], default=0, null=True, verbose_name='สิทธิ์การรักษาพยาบาล'),
        ),
        migrations.AlterField(
            model_name='amedpatient',
            name='ANNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขผู้ป่วยใน'),
        ),
        migrations.AlterField(
            model_name='amedpatient',
            name='HNNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขผู้ป่วยนอก'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='AirforceType',
            field=models.IntegerField(choices=[(0, 'ไม่ระบุ'), (1, 'ทหารประจำการ'), (2, 'พลทหาร'), (3, 'พนง.ราชการ'), (4, 'ลูกจ้างประจำ'), (5, 'ลูกจ้างชั่วคราว'), (6, 'ครอบครัว ทอ.'), (7, 'บุคคลภายนอก')], default=0, null=True, verbose_name='ประเภทข้าราชการ'),
        ),
    ]
