# Generated by Django 3.2.4 on 2021-07-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_auto_20210716_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='IsAirforce',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='ขรก.ทอ.'),
        ),
    ]
