# Generated by Django 3.2.4 on 2021-07-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_patient_isairforce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='EmergencyMobileMobile',
        ),
        migrations.AddField(
            model_name='patient',
            name='EmergencyMobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์ฉุกเฉิน'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='IsAirforce',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ขรก.ทอ.'),
        ),
    ]
