# Generated by Django 3.2.5 on 2021-07-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_auto_20210716_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='CurrentStatus',
            field=models.IntegerField(blank=True, choices=[(1, 'เขียว'), (2, 'เหลืองอ่อน'), (3, 'เหลืองแก่'), (4, 'แดง'), (5, 'หายป่วย'), (6, 'เสียชีวิต'), (7, 'เสี่ยงสูง (ผู้ใกล้ชิด)'), (8, 'ปลอดเชื้อ (ผู้ใกล้ชิด)'), (9, 'ติดเชื้อ (ผู้ใกล้ชิด)')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Treatment',
            field=models.IntegerField(choices=[(1, 'รักษาระยะห่าง'), (2, 'กักตัวอยู่บ้าน'), (3, 'กักตัวรอเตียง'), (4, 'Home Isolation'), (5, 'รพ.สนาม'), (6, 'โรงพยาบาล'), (7, 'ICU')], default=1, null=True),
        ),
    ]
