# Generated by Django 3.2.5 on 2021-07-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_rename_treatment_patient_currenttreatment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuslog',
            old_name='Patient',
            new_name='ThePatient',
        ),
        migrations.RenameField(
            model_name='treatmentlog',
            old_name='Patient',
            new_name='ThePatient',
        ),
    ]
