# Generated by Django 3.2.5 on 2021-07-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0010_auto_20210717_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='CurrentStatus',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'ผู้ป่วยสีเขียว'), (2, 'ผู้ป่วยสีเหลือง'), (3, 'ผู้ป่วยสีส้ม'), (4, 'ผู้ป่วยสีแดง'), (5, 'หายป่วย'), (6, 'เสียชีวิต'), (7, 'ผู้ใกล้ชิดเสี่ยงสูง'), (8, 'ผู้ใกล้ชิดปลอดเชื้อ'), (9, 'ผู้ใกล้ชิดติดเชื้อ')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='CurrentTreatment',
            field=models.IntegerField(choices=[(0, 'ไม่ระบุ'), (1, 'รักษาระยะห่าง'), (2, 'กักตัวอยู่บ้าน'), (3, 'กักตัวรอเตียง'), (4, 'Home Isolation'), (5, 'รพ.สนาม'), (6, 'โรงพยาบาล'), (7, 'ICU')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='Status',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'ผู้ป่วยสีเขียว'), (2, 'ผู้ป่วยสีเหลือง'), (3, 'ผู้ป่วยสีส้ม'), (4, 'ผู้ป่วยสีแดง'), (5, 'หายป่วย'), (6, 'เสียชีวิต'), (7, 'ผู้ใกล้ชิดเสี่ยงสูง'), (8, 'ผู้ใกล้ชิดปลอดเชื้อ'), (9, 'ผู้ใกล้ชิดติดเชื้อ')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentlog',
            name='Treatment',
            field=models.IntegerField(choices=[(0, 'ไม่ระบุ'), (1, 'รักษาระยะห่าง'), (2, 'กักตัวอยู่บ้าน'), (3, 'กักตัวรอเตียง'), (4, 'Home Isolation'), (5, 'รพ.สนาม'), (6, 'โรงพยาบาล'), (7, 'ICU')], default=1, null=True),
        ),
    ]
