# Generated by Django 3.2.5 on 2021-07-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0011_auto_20210718_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='RightMedicalTreatment',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'เบิกจ่ายตรง (กรมบัญชีกลาง)'), (2, 'ประกันสังคม'), (3, 'UC (สปสช.)'), (4, 'เงินสด')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='CurrentStatus',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'ผู้ป่วยสีเขียว'), (2, 'ผู้ป่วยสีเหลืองอ่อน'), (3, 'ผู้ป่วยสีเหลืองเข้ม'), (4, 'ผู้ป่วยสีแดง'), (5, 'หายป่วย'), (6, 'เสียชีวิต'), (7, 'ผู้ใกล้ชิดเสี่ยงสูง'), (8, 'ผู้ใกล้ชิดปลอดเชื้อ'), (9, 'ผู้ใกล้ชิดติดเชื้อ')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='Status',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'ผู้ป่วยสีเขียว'), (2, 'ผู้ป่วยสีเหลืองอ่อน'), (3, 'ผู้ป่วยสีเหลืองเข้ม'), (4, 'ผู้ป่วยสีแดง'), (5, 'หายป่วย'), (6, 'เสียชีวิต'), (7, 'ผู้ใกล้ชิดเสี่ยงสูง'), (8, 'ผู้ใกล้ชิดปลอดเชื้อ'), (9, 'ผู้ใกล้ชิดติดเชื้อ')], default=1, null=True),
        ),
    ]
