# Generated by Django 3.2.5 on 2021-07-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0013_alter_patient_confirmedpatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PersonID',
            field=models.CharField(blank=True, default='-', max_length=13, null=True, unique=True, verbose_name='เลขบัตรประชาชน'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='RightMedicalTreatment',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'เบิกจ่ายตรง (กรมบัญชีกลาง)'), (2, 'ประกันสังคม'), (3, 'UC (สปสช.)'), (4, 'เงินสด')], default=0, null=True, verbose_name='สิทธิ์การรักษาพยาบาล'),
        ),
    ]
