# Generated by Django 3.2.5 on 2021-07-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0014_auto_20210719_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PersonID',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='เลขบัตรประชาชน'),
        ),
    ]
