# Generated by Django 3.2.5 on 2021-07-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('User_AF_CMO', 'User AF CMO'), ('User_Unit_CMO', 'User Unit CMO'), ('User_PMD', 'User PMD'), ('User_CRC', 'User CRC'))},
        ),
    ]
