# Generated by Django 3.2.5 on 2021-07-18 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0006_alter_user_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('User_AF_CMO', 'User AF CMO'), ('User_Unit_CMO', 'User Unit CMO'), ('User_PMD', 'User PMD'), ('User_CRC', 'User CRC'), ('User_Hospital', 'User Hospital'))},
        ),
    ]
